services:
  typesense:
    image: typesense/typesense:27.1
    restart: on-failure
    container_name: typeserver
    environment:
      - API_KEY="123456789"
      - DATA_DIR=$HOME/typesense-data
    ports:
      - "8108:8108"
    volumes:
      - ./data:/data
    command: >
      --api-key=123456789
      --data-dir=/data
      --enable-cors
            